import { Pokemon } from './pokemon';

export const POKEMONS: Pokemon[] = [
  {
    id: 1,
    name: 'Bulbizarre',
    healthPoints: 25,
    combatPower: 5,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
    types: ['Plante', 'Poison'],
    creationDate: new Date(),
  },
  {
    id: 2,
    name: 'Salamèche',
    healthPoints: 28,
    combatPower: 6,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png',
    types: ['Feu'],
    creationDate: new Date(),
  },
  {
    id: 3,
    name: 'Carapuce',
    healthPoints: 21,
    combatPower: 4,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png',
    types: ['Eau'],
    creationDate: new Date(),
  },
  {
    id: 4,
    name: 'Aspicot',
    healthPoints: 16,
    combatPower: 2,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png',
    types: ['Insecte', 'Poison'],
    creationDate: new Date(),
  },
  {
    id: 5,
    name: 'Roucool',
    healthPoints: 30,
    combatPower: 7,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png',
    types: ['Normal', 'Vol'],
    creationDate: new Date(),
  },
  {
    id: 6,
    name: 'Rattata',
    healthPoints: 18,
    combatPower: 6,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png',
    types: ['Normal'],
    creationDate: new Date(),
  },
  {
    id: 7,
    name: 'Piafabec',
    healthPoints: 14,
    combatPower: 5,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png',
    types: ['Normal', 'Vol'],
    creationDate: new Date(),
  },
  {
    id: 8,
    name: 'Abo',
    healthPoints: 16,
    combatPower: 4,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png',
    types: ['Poison'],
    creationDate: new Date(),
  },
  {
    id: 9,
    name: 'Pikachu',
    healthPoints: 21,
    combatPower: 7,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png',
    types: ['Electrik'],
    creationDate: new Date(),
  },
  {
    id: 10,
    name: 'Sabelette',
    healthPoints: 19,
    combatPower: 3,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png',
    types: ['Normal'],
    creationDate: new Date(),
  },
  {
    id: 11,
    name: 'Mélofée',
    healthPoints: 25,
    combatPower: 5,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png',
    types: ['Fée'],
    creationDate: new Date(),
  },
  {
    id: 12,
    name: 'Groupix',
    healthPoints: 17,
    combatPower: 8,
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png',
    types: ['Feu'],
    creationDate: new Date(),
  },
];
